background_opacity: 0.6
key_bindings:
  - { key: Escape, mods: Control, mode: ~Search, action: ToggleViMode }
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
  - { key: O, mods: Control|Shift, chars: "\x1b[79;5u"                }
  - { key: I, mods: Control|Shift, chars: "\x1b[73;5u"                }
  - { key: A, mods: Shift, mode: Vi, action: Last }
  - { key: I, mods: Shift, mode: Vi, action: First }
colors:
  #cursor:
    #cursor: '#f92aad'
    #text: '#af6df9'
  primary:
    foreground: '#f0eff1'
      #background: '#262335'
  selection:
    background: '#f0eff1'
    text: '#f0eff1'
  normal:
    #black:   '#ffcc00'
    red:     '#f92aad'
    green:   '#ffcc00'
      #yellow:  '#ffcc00'
    blue:    '#af6df9'
    magenta: '#ffcc00'
    cyan:    '#f92aad'
    white:   '#ffcc00'

font:
  normal:
    family: Jetbrains Mono
  size: 20

cursor:
  style:
    shape: Block
